### ISSUE TITLE
builtins.ImportError: No module named 'exceptions'

### ISSUE THREAD

**Issue by WebDevelopNemanja** [deldotdr/txRedis#56]
txredis 2.4 installed on python3.4 over easy_install3
after starting crossbar router, this error came up.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/autobahn/wamp/protocol.py", line 842, in onMessage
    on_reply = txaio.as_future(endpoint.fn, _invoke_args, *_invoke_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/txaio/tx.py", line 408, in as_future
    return maybeDeferred(fun, _args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(_args, *_kw)
  File "/usr/local/lib/python3.4/dist-packages/crossbar/worker/router.py", line 643, in start_router_component
    create_component = _appsession_loader(config)
--- <exception caught here> ---
  File "/usr/local/lib/python3.4/dist-packages/crossbar/worker/__init__.py", line 58, in _appsession_loader
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import

  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load

  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 1129, in _exec

  File "<frozen importlib._bootstrap>", line 1471, in exec_module

  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed

  File "/home/www/work/dc/example/crossbar/components/main.py", line 7, in <module>
    from helpers.util import success
  File "/home/www/work/dc/example/backend/crossbar/helpers/util.py", line 6, in <module>
    from txredis.client import RedisClient
  File "/usr/local/lib/python3.4/dist-packages/txredis-2.4-py3.4.egg/txredis/**init**.py", line 39, in <module>

builtins.ImportError: No module named 'exceptions'

**Comment by wiml** [comment]
Looks like txredis generally doesn't support Python 3. The patches in PR #58 might help. From the forks tab, @tdsmith, @tomwardill and @Enforcer all seem to have done some py3 support work.
